"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { BarChart3, Bell, BriefcaseBusiness, ChevronDown, FileText, Globe2, Image, ImagePlus, LayoutDashboard, Mail, Menu, Newspaper, Pencil, Plus, Search, Settings, Upload, Users, X } from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { readDemoContent, resetDemoContent, writeDemoContent, type DemoContent } from "@/lib/demo-cms";
import "./admin.css";

type ContentRow={id:string;title:string;type:string;status:string;author:string;updated:string;views:string;slug?:string;summary?:string};
const seedRows:ContentRow[] = [
  { id:"demo-1",title:"Ship more, save more this September", type:"Campaign", status:"PUBLISHED", author:"Thiri Aye", updated:"15 Sep 2026, 09:42", views:"12,480" },
  { id:"demo-2",title:"Yangon–Mandalay 24-hour express lane", type:"Service", status:"PUBLISHED", author:"Min Khant", updated:"14 Sep 2026, 16:18", views:"8,216" },
  { id:"demo-3",title:"New service points in Shan State", type:"News", status:"PENDING_REVIEW", author:"Su Myat", updated:"14 Sep 2026, 11:05", views:"—" },
  { id:"demo-4",title:"Operations Supervisor — Mandalay", type:"Career", status:"DRAFT", author:"HR Team", updated:"13 Sep 2026, 14:30", views:"—" },
  { id:"demo-5",title:"International shipping guide 2026", type:"Article", status:"PUBLISHED", author:"Nyein Chan", updated:"12 Sep 2026, 10:12", views:"5,904" },
];

const nav = [
  [LayoutDashboard,"Overview"],[Image,"Banners"],[FileText,"Pages"],[Globe2,"Services"],
  [Newspaper,"News & campaigns"],[BriefcaseBusiness,"Careers"],[Mail,"Contact"],[Users,"Users"],[Settings,"Settings"]
] as const;

export default function AdminPage(){
  const [active,setActive]=useState("Overview");
  const [sidebar,setSidebar]=useState(false);
  const [dialog,setDialog]=useState(false);
  const [notice,setNotice]=useState("");
  const [rows,setRows]=useState<ContentRow[]>(seedRows);
  const [configured,setConfigured]=useState(false);
  const [form,setForm]=useState({type:"BANNER",title:"Deliver farther with MyLogistics",summary:"Fast, reliable delivery across Myanmar.",body:"FEATURED CAMPAIGN",imageUrl:"/mylogistics-hero.png",ctaLabel:"Learn more",ctaUrl:"#services"});
  const [imagePreview,setImagePreview]=useState("/mylogistics-hero.png");
  const toRows=(items:DemoContent[]):ContentRow[]=>items.map(item=>({id:item.id,title:item.title,type:item.type,status:item.status,author:item.createdBy,updated:new Date(item.updatedAt).toLocaleString(),views:"—",slug:item.slug,summary:item.summary}));
  useEffect(()=>{fetch("/api/cms/admin/content").then(r=>r.json()).then(data=>{setConfigured(Boolean(data.configured));if(data.items?.length)setRows(data.items.map((item:any)=>({id:item.id,title:item.title,type:item.type,status:item.status,author:item.createdBy,updated:new Date(item.updatedAt).toLocaleString(),views:"—",slug:item.slug,summary:item.summary})));else setRows(toRows(readDemoContent()))}).catch(()=>setRows(toRows(readDemoContent())))},[]);
  const flash=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(""),3000)};
  const save=async()=>{const slug=form.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");try{const r=await fetch("/api/cms/admin/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,slug,locale:"en",sortOrder:0})});if(!r.ok)throw new Error();const item=await r.json();setRows(current=>[{id:item.id,title:item.title,type:item.type,status:item.status,author:item.createdBy,updated:new Date(item.updatedAt).toLocaleString(),views:"—"},...current]);setDialog(false);flash("Draft saved to PostgreSQL.")}catch{const item:DemoContent={...form,id:crypto.randomUUID(),slug,status:"DRAFT",createdBy:"Nguyen Luan",updatedAt:new Date().toISOString()};const items=[item,...readDemoContent()];writeDemoContent(items);setRows(toRows(items));setDialog(false);flash("Draft saved to the demo database.")}};
  const pickImage=(file?:File)=>{if(!file)return;setImagePreview(URL.createObjectURL(file));flash("Image selected for preview. Add a hosted image URL before saving.")};
  const workflow=async(row:ContentRow)=>{const action=row.status==="DRAFT"?"submit":row.status==="PENDING_REVIEW"?"publish":row.status==="PUBLISHED"?"archive":"";if(!action)return;try{if(!configured)throw new Error();const r=await fetch(`/api/cms/admin/content/${row.id}/${action}`,{method:"POST"});if(!r.ok)throw new Error();const updated=await r.json();setRows(all=>all.map(x=>x.id===row.id?{...x,status:updated.status,updated:new Date(updated.updatedAt).toLocaleString()}:x));flash(action==="publish"?"Published — public website will read this content.":"Workflow status updated.")}catch{const nextStatus:DemoContent["status"]=action==="submit"?"PENDING_REVIEW":action==="publish"?"PUBLISHED":"ARCHIVED";const items=readDemoContent().map(item=>item.id===row.id?{...item,status:nextStatus,updatedAt:new Date().toISOString()}:item);writeDemoContent(items);setRows(toRows(items));flash(action==="publish"?"Published to the demo website.":"Demo workflow status updated.")}};
  const resetDemo=()=>{const items=resetDemoContent();setRows(toRows(items));flash("Demo database reset.")};
  return <main className="cms">
    <aside className={sidebar?"cms-sidebar open":"cms-sidebar"}>
      <div className="cms-brand"><img src="/mylogistics-favicon.png" alt=""/><div><b>MyLogistics</b><small>CONTENT HUB</small></div><button onClick={()=>setSidebar(false)} aria-label="Close navigation"><X/></button></div>
      <nav>{nav.map(([Icon,label])=><button key={label} className={active===label?"active":""} onClick={()=>{setActive(label);setSidebar(false)}}><Icon/>{label}{label==="News & campaigns"&&<em>12</em>}</button>)}</nav>
      <div className="cms-sidebar-foot"><span>EN</span><div><b>English</b><small>Myanmar website</small></div><ChevronDown/></div>
    </aside>
    <section className="cms-main">
      <header className="cms-topbar"><button className="cms-menu" onClick={()=>setSidebar(true)}><Menu/></button><div className="cms-search"><Search/><input placeholder="Search content, pages or users..."/></div><div className="cms-top-actions"><Link href="/" target="_blank"><Globe2/> View website</Link><button aria-label="Notifications"><Bell/><i/></button><div className="cms-user"><span>NL</span><div><b>Nguyen Luan</b><small>Administrator</small></div><ChevronDown/></div></div></header>
      <div className="cms-content">
        <div className="cms-title"><div><p>Tuesday, 15 September 2026</p><h1>{active}</h1><span>Manage website content and publishing activity. <b className={configured?"api-on":"api-off"}>{configured?"PostgreSQL connected":"Demo database active"}</b>{!configured&&<button className="reset-demo" onClick={resetDemo}>Reset data</button>}</span></div><button onClick={()=>setDialog(true)}><Plus/> Create content</button></div>
        <div className="cms-stats"><article><span className="red"><FileText/></span><div><small>Total content</small><strong>148</strong><em>+8 this month</em></div></article><article><span className="blue"><Globe2/></span><div><small>Published</small><strong>126</strong><em>85% of content</em></div></article><article><span className="gold"><Pencil/></span><div><small>Drafts</small><strong>14</strong><em>4 need review</em></div></article><article><span className="green"><BarChart3/></span><div><small>Views this month</small><strong>84.2K</strong><em>+18.6% vs last month</em></div></article></div>
        <div className="cms-grid"><section className="cms-panel content-panel"><div className="panel-head"><div><h2>Recent content</h2><p>Latest updates across the website</p></div><div><button className="filter">All content <ChevronDown/></button><button onClick={()=>setDialog(true)}><Plus/> Add new</button></div></div><Table><TableHeader><TableRow><TableHead>Content</TableHead><TableHead>Status</TableHead><TableHead>Author</TableHead><TableHead>Last updated</TableHead><TableHead className="views">Views</TableHead><TableHead>Workflow</TableHead></TableRow></TableHeader><TableBody>{rows.slice(0,8).map(row=><TableRow key={row.id}><TableCell><div className="content-name"><span className={`type-${row.type.toLowerCase().split(" ")[0]}`}>{row.type==="CAMPAIGN"?<Image/>:row.type==="CAREER"?<BriefcaseBusiness/>:<FileText/>}</span><div><b>{row.title}</b><small>{row.type}</small></div></div></TableCell><TableCell><Badge className={`cms-badge ${row.status.toLowerCase()}`}>{row.status.replace("_"," ")}</Badge></TableCell><TableCell>{row.author}</TableCell><TableCell>{row.updated}</TableCell><TableCell className="views">{row.views}</TableCell><TableCell><button className="flow-action" onClick={()=>workflow(row)}>{row.status==="DRAFT"?"Submit":row.status==="PENDING_REVIEW"?"Publish":row.status==="PUBLISHED"?"Archive":"Done"}</button></TableCell></TableRow>)}</TableBody></Table><div className="table-foot"><span>Showing {Math.min(rows.length,8)} items</span><button>View all content</button></div></section>
        <aside className="cms-panel quick-panel"><div className="panel-head"><div><h2>Publishing queue</h2><p>Scheduled and awaiting review</p></div></div><div className="queue"><article><i className="scheduled"/><div><b>New service points in Shan State</b><small>Scheduled for 16 Sep · 08:00</small></div><span>NEWS</span></article><article><i className="review"/><div><b>Thingyan holiday delivery schedule</b><small>Waiting for your review</small></div><span>NOTICE</span></article><article><i className="draft"/><div><b>Operations Supervisor — Mandalay</b><small>Last edited 2 days ago</small></div><span>CAREER</span></article></div><button className="queue-link">Open publishing calendar</button></aside></div>
        <section className="cms-panel banner-panel"><div className="panel-head"><div><h2>Homepage banners</h2><p>Live campaign rotation on the public website</p></div><button onClick={()=>{setActive("Banners");setDialog(true);setForm(current=>({...current,type:"BANNER"}))}}><ImagePlus/> Add banner</button></div><div className="banner-list">{["Scale your business, we handle the miles.","Yangon to Mandalay in just 24 hours.","Myanmar to the world, made simpler."].map((title,index)=><div className="banner-preview has-photo" key={title}><img src="/mylogistics-hero.png" alt=""/><div><small>CAMPAIGN 0{index+1}</small><b>{title}</b><span>{index===0?"Live until 30 Sep":"Always active"}</span></div></div>)}</div></section>
      </div>
    </section>
    {notice&&<div className="cms-toast">{notice}</div>}
    <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="cms-dialog"><DialogHeader><DialogTitle>{form.type==="BANNER"?"Add homepage banner":"Create new content"}</DialogTitle><DialogDescription>Create a draft, then submit it for review and publishing.</DialogDescription></DialogHeader><div className="cms-dialog-body"><label>Content type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="BANNER">Banner</option><option value="NEWS">News</option><option value="CAMPAIGN">Campaign</option><option value="SERVICE">Service</option><option value="CAREER">Career</option></select></label>{form.type==="BANNER"&&<div className="banner-upload"><div className="banner-upload-preview"><img src={imagePreview||form.imageUrl} alt="Banner preview"/></div><div><b>Banner image</b><span>Recommended 1920 × 720 px, JPG or PNG.</span><label className="upload-button"><Upload/> Choose image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>pickImage(e.target.files?.[0])}/></label></div></div>}<label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Short description<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label>{form.type==="BANNER"&&<><label>Image URL<input value={form.imageUrl} placeholder="https://.../banner.jpg" onChange={e=>{setForm({...form,imageUrl:e.target.value});setImagePreview(e.target.value)}}/></label><div className="cms-form-row"><label>Eyebrow<input value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><label>Button label<input value={form.ctaLabel} onChange={e=>setForm({...form,ctaLabel:e.target.value})}/></label></div><label>Button link<input value={form.ctaUrl} onChange={e=>setForm({...form,ctaUrl:e.target.value})}/></label></>}</div><DialogFooter><button className="cancel" onClick={()=>setDialog(false)}>Cancel</button><button className="save" onClick={save}>Save draft</button></DialogFooter></DialogContent></Dialog>
  </main>
}
