"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowRight, Box, BriefcaseBusiness, Building2, Calculator, ChevronDown, Clock3, Globe2, Headphones, LocateFixed, Mail, MapPin, Menu, PackageCheck, Phone, Search, ShieldCheck, Smartphone, Truck, Warehouse, X } from "lucide-react";
import { readDemoContent } from "@/lib/demo-cms";

const services = [
  { icon: Truck, title: "Express Delivery", text: "Fast, reliable nationwide delivery for every shipment.", tone: "red" },
  { icon: Globe2, title: "International Shipping", text: "Connect your business to regional and global markets.", tone: "blue" },
  { icon: Warehouse, title: "Warehousing", text: "Flexible fulfillment and inventory solutions at scale.", tone: "gold" },
  { icon: Building2, title: "Business Solutions", text: "Tailored logistics for e-commerce and enterprises.", tone: "green" },
];
const news = [
  { day: "12", month: "SEP", tag: "Campaign", title: "Ship more, save more with our September business offers", color: "campaign-one" },
  { day: "05", month: "SEP", tag: "Network", title: "New service points bring delivery closer to your community", color: "campaign-two" },
  { day: "28", month: "AUG", tag: "Company", title: "Building a smarter, more connected logistics network", color: "campaign-three" },
];
const fallbackBanners = [
  { label:"NEW BUSINESS CAMPAIGN", title:"Scale your business,", accent:"we handle the miles.", text:"Save up to 25% on domestic shipping for new business accounts this September.", action:"Register for the offer", theme:"banner-red", imageUrl:"/mylogistics-hero.png" },
  { label:"EXPRESS DELIVERY", title:"Yangon to Mandalay", accent:"in just 24 hours.", text:"A faster express lane for urgent documents and parcels, with end-to-end tracking.", action:"Explore express delivery", theme:"banner-blue", imageUrl:"/mylogistics-hero.png" },
  { label:"INTERNATIONAL SHIPPING", title:"Myanmar to the world,", accent:"made simpler.", text:"Reliable cross-border delivery, customs support and transparent shipment visibility.", action:"Get a shipping quote", theme:"banner-gold", imageUrl:"/mylogistics-hero.png" },
];

export default function Home() {
  const [activeTool, setActiveTool] = useState("tracking");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [message, setMessage] = useState("");
  const [showResult, setShowResult] = useState(false);
  const [banners, setBanners] = useState(fallbackBanners);
  const [bannerIndex, setBannerIndex] = useState(0);
  const [bannerPaused, setBannerPaused] = useState(false);
  const touchStartX = useRef<number | null>(null);
  const changeBanner = (direction:number) => setBannerIndex(current => (current + direction + banners.length) % banners.length);
  useEffect(()=>{const mapBanners=(items:any[])=>items.filter(item=>item.type==="BANNER"&&item.status==="PUBLISHED").map((item:any,index:number)=>({label:item.body||"LATEST CAMPAIGN",title:item.title,accent:"",text:item.summary||"",action:item.ctaLabel||"Learn more",theme:["banner-red","banner-blue","banner-gold"][index%3],imageUrl:item.imageUrl||"/mylogistics-hero.png"}));const loadDemo=()=>{const items=mapBanners(readDemoContent());if(items.length){setBanners(items);setBannerIndex(0)}};fetch("/api/cms/public?type=BANNER&locale=en").then(r=>r.json()).then(data=>{if(data.items?.length)setBanners(mapBanners(data.items));else loadDemo()}).catch(loadDemo);window.addEventListener("mylogistics-cms-updated",loadDemo);window.addEventListener("storage",loadDemo);return()=>{window.removeEventListener("mylogistics-cms-updated",loadDemo);window.removeEventListener("storage",loadDemo)}},[]);
  useEffect(()=>{document.documentElement.style.setProperty("--hero-image",`url("${banners[bannerIndex]?.imageUrl||"/mylogistics-hero.png"}")`)},[banners,bannerIndex]);
  useEffect(() => {
    if (bannerPaused) return;
    const timer = window.setInterval(() => changeBanner(1), 5500);
    return () => window.clearInterval(timer);
  }, [bannerPaused]);
  const selectTool = (name:string) => { setActiveTool(name); setQuery(""); setMessage(""); setShowResult(false); };
  const submit = () => {
    if (!query.trim()) return setMessage("Please enter the required information.");
    const labels: Record<string,string> = { tracking:"Tracking", rate:"Rate estimate", branch:"Branch search" };
    setMessage(`${labels[activeTool]} result — sample data`); setShowResult(true);
  };
  return <main>
    <div className="utility-bar"><div className="shell utility-inner"><span><Phone size={14}/> Hotline: <b>+959662247247</b></span><div><a href="#news">News</a><a href="#careers">Careers</a><button><Globe2 size={14}/> EN <ChevronDown size={13}/></button></div></div></div>
    <header className="main-header"><div className="shell nav-wrap">
      <a href="#top" className="brand" aria-label="MyLogistics home"><img className="brand-logo" src="/mylogistics-logo.png" alt="MyLogistics"/></a>
      <nav className={mobileOpen?"nav-links open":"nav-links"}>{[["About us","about"],["Services","services"],["Network","network"],["News","news"],["Careers","careers"],["Contact","contact"]].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMobileOpen(false)}>{label}</a>)}</nav>
      <a className="portal-btn" href="/admin" target="_blank">Manage shipments <ArrowRight size={16}/></a>
      <button className="menu-btn" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Toggle menu">{mobileOpen?<X/>:<Menu/>}</button>
    </div></header>
    <section className={`hero ${banners[bannerIndex].theme}`} id="top" onMouseEnter={()=>setBannerPaused(true)} onMouseLeave={()=>setBannerPaused(false)} onTouchStart={e=>{touchStartX.current=e.touches[0].clientX;setBannerPaused(true)}} onTouchEnd={e=>{if(touchStartX.current!==null){const distance=e.changedTouches[0].clientX-touchStartX.current;if(Math.abs(distance)>45)changeBanner(distance<0?1:-1)}touchStartX.current=null;setBannerPaused(false)}}><div className="hero-grid"/>{banners.map((banner,index)=><div className={`shell hero-content banner-layer ${index===bannerIndex?"active":""}`} key={`${banner.label}-${index}`} aria-hidden={index!==bannerIndex}><div className="hero-copy"><span className="eyebrow">{banner.label}</span><h1>{banner.title}<br/><em>{banner.accent}</em></h1><p>{banner.text}</p><div className="hero-actions"><a href="#services" className="primary-btn">{banner.action} <ArrowRight size={18}/></a><a href="#network" className="text-btn"><MapPin size={18}/> Find a service point</a></div><div className="banner-dots" aria-label="Select campaign banner">{banners.map((item,i)=><button key={`${item.label}-${i}`} className={i===bannerIndex?"active":""} onClick={()=>setBannerIndex(i)} aria-label={`Banner ${i+1}`}/>)}</div></div><div className="hero-visual"><div className="campaign-badge"><span>UP TO</span><strong>{index===0?"25%":index===1?"24H":"20+"}</strong><small>{index===0?"OFF":index===1?"EXPRESS":"COUNTRIES"}</small></div><div className="map-shape"><i className="pin pin-a"/><i className="pin pin-b"/><i className="pin pin-c"/><Truck className="truck-icon"/></div><div className="floating-card"><PackageCheck size={22}/><span><b>Delivered safely</b><small>Every mile, under control</small></span></div></div></div>)}</section>
    <section className="quick-wrap" aria-label="Customer service tools"><div className="shell quick-card"><div className="tool-tabs"><button className={activeTool==="tracking"?"active":""} onClick={()=>selectTool("tracking")}><Search/> Track shipment</button><button className={activeTool==="rate"?"active":""} onClick={()=>selectTool("rate")}><Calculator/> Estimate rate</button><button className={activeTool==="branch"?"active":""} onClick={()=>selectTool("branch")}><LocateFixed/> Find a branch</button></div><div className="tool-form"><div><label>{activeTool==="tracking"?"Enter tracking number":activeTool==="rate"?"Enter origin and destination":"Enter township or city"}</label><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder={activeTool==="tracking"?"Try: MYL123456789":activeTool==="rate"?"Try: Yangon → Mandalay":"Try: Yangon"}/></div><button onClick={submit}>{activeTool==="tracking"?"Track now":activeTool==="rate"?"Calculate":"Search"} <ArrowRight size={18}/></button></div>{message&&<p className="form-message" role="status">{message}</p>}{showResult&&<div className="demo-result">{activeTool==="tracking"&&<><div className="result-head"><span className="status-pill">In transit</span><b>MYL123456789</b><small>Estimated delivery: 16 Sep 2026</small></div><div className="timeline"><div className="done"><i/><span><b>Parcel received</b><small>Yangon Hub · 14 Sep, 09:15</small></span></div><div className="done"><i/><span><b>Departed sorting center</b><small>Yangon Hub · 14 Sep, 21:40</small></span></div><div className="current"><i/><span><b>In transit to destination</b><small>Mandalay route · Today, 06:25</small></span></div><div><i/><span><b>Out for delivery</b><small>Waiting for next update</small></span></div></div></>}{activeTool==="rate"&&<><div className="rate-route"><span><small>FROM</small><b>Yangon</b></span><ArrowRight/><span><small>TO</small><b>Mandalay</b></span><span><small>WEIGHT</small><b>2.0 kg</b></span></div><div className="rate-options"><div><span><Truck/><b>Express</b><small>1–2 business days</small></span><strong>6,500 MMK</strong></div><div><span><Box/><b>Standard</b><small>2–4 business days</small></span><strong>4,200 MMK</strong></div></div></>}{activeTool==="branch"&&<div className="branch-list"><div><MapPin/><span><b>Yangon Central Service Point</b><small>No. 123, Bogyoke Aung San Road · 0.8 km</small><em>Open now · Closes 6:00 PM</em></span><button>Directions</button></div><div><MapPin/><span><b>Sanchaung Service Point</b><small>Pyay Road, Sanchaung Township · 2.4 km</small><em>Open now · Closes 5:30 PM</em></span><button>Directions</button></div></div>}</div>}</div></section>
    <section className="section shell" id="services"><div className="section-heading"><div><span className="kicker">WHAT WE DELIVER</span><h2>Solutions for every journey</h2></div><p>One trusted logistics partner—from first mile to final delivery.</p></div><div className="service-grid">{services.map(({icon:Icon,title,text,tone})=><article className={`service-card ${tone}`} key={title}><span className="service-icon"><Icon/></span><h3>{title}</h3><p>{text}</p><a href="#contact">Learn more <ArrowRight size={16}/></a></article>)}</div></section>
    <section className="network-section" id="network"><div className="shell network-grid"><div className="network-copy"><span className="kicker light">OUR NETWORK</span><h2>Closer to every<br/>community.</h2><p>A growing nationwide network, connected by technology and powered by people who know every route.</p><a href="#top" className="outline-btn">Explore our network <ArrowRight size={18}/></a></div><div className="stats-grid"><div><strong>200+</strong><span>Service points</span></div><div><strong>15</strong><span>Regions & states</span></div><div><strong>98%</strong><span>On-time delivery</span></div><div><strong>24/7</strong><span>Shipment visibility</span></div></div></div></section>
    <section className="section shell" id="about"><div className="promise-grid"><div className="promise-visual"><Box/><span className="pulse-dot one"/><span className="pulse-dot two"/><span className="pulse-dot three"/></div><div className="promise-copy"><span className="kicker">THE MYLOGISTICS PROMISE</span><h2>Built for certainty.<br/>Driven by care.</h2><p>Every parcel represents a promise. Our teams, technology and operating network work together to keep that promise—safely and transparently.</p><ul><li><ShieldCheck/> Secure handling at every step</li><li><Clock3/> Reliable, predictable delivery</li><li><Headphones/> Support when you need it</li></ul></div></div></section>
    <section className="news-section" id="news"><div className="shell"><div className="section-heading"><div><span className="kicker">LATEST UPDATES</span><h2>News & campaigns</h2></div><a href="#news" className="view-all">View all news <ArrowRight size={17}/></a></div><div className="news-grid">{news.map(item=><article className="news-card" key={item.title}><div className={`news-art ${item.color}`}><span>{item.day}<small>{item.month}</small></span><Truck/></div><div className="news-body"><span>{item.tag}</span><h3>{item.title}</h3><a href="#contact">Read story <ArrowRight size={15}/></a></div></article>)}</div></div></section>
    <section className="career-cta" id="careers"><div className="shell career-inner"><div><BriefcaseBusiness/><span><b>Move your career forward with us.</b><small>Join a team connecting people, businesses and opportunities.</small></span></div><a href="#contact">View open positions <ArrowRight size={17}/></a></div></section>
    <footer id="contact"><div className="shell footer-grid"><div><a href="#top" className="brand footer-brand"><img className="brand-logo footer-logo" src="/mylogistics-logo.png" alt="MyLogistics"/></a><p>Reliable delivery and logistics solutions across Myanmar.</p><div className="socials"><a href="#contact" aria-label="Facebook">f</a><a href="#contact" aria-label="Instagram">ig</a><a href="#contact" aria-label="Youtube">▶</a></div></div><div><h3>Company</h3><a href="#about">About us</a><a href="#news">News</a><a href="#careers">Careers</a></div><div><h3>Services</h3><a href="#services">Express delivery</a><a href="#services">International</a><a href="#services">Warehousing</a></div><div><h3>Contact</h3><span><Phone/> +959662247247</span><span><Mail/> support@mylogistics.com</span><span><MapPin/> Yangon, Myanmar</span></div></div><div className="shell footer-bottom"><span>© 2026 MyLogistics. All rights reserved.</span><span>Privacy Policy · Terms of Service</span></div></footer>
    <a href="#contact" className="support-fab" aria-label="Contact support"><Smartphone/></a>
  </main>;
}
